"""Add Student and ExamRegistration models

Revision ID: 5f796180575e
Revises: 9a81aef09e90
Create Date: 2025-04-27 21:16:27.894539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f796180575e'
down_revision = '9a81aef09e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_full_name'), ['full_name'], unique=False)

    op.create_table('exam_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('registration_type', sa.String(length=50), nullable=False),
    sa.Column('study_type', sa.String(length=50), nullable=False),
    sa.Column('seat_code', sa.String(length=10), nullable=True),
    sa.Column('hall_name', sa.String(length=50), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name='fk_exam_registration_exam'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_exam_registration_student'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_student')
    )
    with op.batch_alter_table('exam_registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_registration_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_registration_hall_name'), ['hall_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_registration_registration_type'), ['registration_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_registration_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_registration_study_type'), ['study_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_registration_study_type'))
        batch_op.drop_index(batch_op.f('ix_exam_registration_student_id'))
        batch_op.drop_index(batch_op.f('ix_exam_registration_registration_type'))
        batch_op.drop_index(batch_op.f('ix_exam_registration_hall_name'))
        batch_op.drop_index(batch_op.f('ix_exam_registration_exam_id'))

    op.drop_table('exam_registration')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_full_name'))

    op.drop_table('student')
    # ### end Alembic commands ###
