"""Add absent_count to ExamAbsence table

Revision ID: 704d12e9a1f8
Revises: 
Create Date: 2025-04-26 02:43:19.219740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704d12e9a1f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_absence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absent_count', sa.Integer(), nullable=True))
        batch_op.alter_column('absent_students_info',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_absence', schema=None) as batch_op:
        batch_op.alter_column('absent_students_info',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('absent_count')

    # ### end Alembic commands ###
