"""Add PdfReviewData table

Revision ID: 925282a7e6dc
Revises: xyz123abc
Create Date: 2025-04-30 23:46:18.582776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925282a7e6dc'
down_revision = 'xyz123abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_review_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('uploader_user_id', sa.Integer(), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.Column('parsed_students_json', sa.Text(), nullable=True),
    sa.Column('parsing_errors_json', sa.Text(), nullable=True),
    sa.Column('extracted_halls_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdf_review_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_review_data_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_review_data_upload_timestamp'), ['upload_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_review_data_uploader_user_id'), ['uploader_user_id'], unique=False)

    with op.batch_alter_table('exam_absence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exam_absence_recorded_by_user', type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    with op.batch_alter_table('exam_absence', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_exam_absence_recorded_by_user', 'user', ['recorded_by_user_id'], ['id'])

    with op.batch_alter_table('pdf_review_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_review_data_uploader_user_id'))
        batch_op.drop_index(batch_op.f('ix_pdf_review_data_upload_timestamp'))
        batch_op.drop_index(batch_op.f('ix_pdf_review_data_exam_id'))

    op.drop_table('pdf_review_data')
    # ### end Alembic commands ###
